locals {
  namespace                = "observ-${var.suffix}"
  rg_name                  = "observ-${var.suffix}"
  storage_account_name     = "observ${var.suffix}"
  storage_container_name   = "observ${var.suffix}"
  iothub_name              = "observ-iothub-${var.suffix}"
  device_id                = "observ-device-${var.suffix}"
  pg_server_name           = "observ-${var.suffix}"
  ams_account_name         = "observ${var.suffix}"
  aks_cloud_name           = "observ-cloud-${var.suffix}"
  aks_cloud_dns_prefix     = "observ-cloud-${var.suffix}"
  aks_cloud_public_ip_name = "observ-cloud-public-ip-${var.suffix}"
  cloud_helm_release_name  = "observ-cloud-${var.suffix}"
  aks_edge_name            = "observ-edge-${var.suffix}"
  aks_edge_dns_prefix      = "observ-edge-${var.suffix}"
  aks_edge_public_ip_name  = "observ-edge-public-ip-${var.suffix}"
  edge_helm_release_name   = "observ-edge-${var.suffix}"
  az_pg_db_name            = "observ${var.suffix}"
  az_pg_db_username        = "observ${var.suffix}"
  az_pg_db_password        = "observ${var.suffix}"
  az_pg_firewall_rule_name = "allow_terraform_${var.suffix}"
  eventhub_namespace       = "eventhub-namespace-${var.suffix}"
  eventhub_name            = "eventhub-${var.suffix}"
  eventhub_auth_rule_name  = "eventhub-auth-rule-${var.suffix}"
  eventhub_consumer_group  = "eventhub-consumer-group-${var.suffix}"
  web_secret_key           = "observ${var.suffix}"
}
